### ISSUE TITLE
Autogenerate lc3test xml files

### ISSUE THREAD

**Issue by ausbin** [zucchini/zucchini#34]
lc3test xml files are annoying as heck to edit by hand, so generate them based on some kind of abbreviated syntax in the assignment config

Need to have this by HW6

**Comment by skyman** [comment]
I feel like it's good to have the actual tests' contents outside of the zucchini config (as it is with circuitsim, junit, libcheck, etc) and in separate files. Especially relevant since we have to export them into XML to give to students anyway.

This sounds to me like something to change with complx (i.e. if it could parse some sweet YAML that supports arrays and whatnot much better than XML) and/or something we can implement with a nice and small jquery app that lets you make the XML config easily.

**Comment by ausbin** [comment]
Agreed, this was a desperation idea before you did the xml work

**Comment by skyman** [comment]
I will try to come up with some sort of good way of producing these test files, though.
