### ISSUE TITLE
Generate, upload grader logs

### ISSUE THREAD

**Issue by ausbin** [zucchini/zucchini#37]
Need this pretty bad t b h

**Comment by pjztam** [comment]
Is anybody working on this?

**Comment by ausbin** [comment]
go for itOn Jan 12, 2018 9:04 PM, Patrick Tam <notifications@github.com> wrote:Is anybody working on this?

**Comment by pjztam** [comment]
As I see it, there are four ways of generating grader logs

## 1 - The T-Square Way

Take all the test names that fail, and dump that into a comment on the canvas submission. That's basically what we did for T-Square, but I think that we really shouldn't do it this way. 

If a lot of tests fail, it turns into this huge jumble of text in the tiny little text box that's basically unreadable.

## 2 - Dumping test statuses into a file

We have four different fields: test status, test name, test description, test value. All these fields can be obtained from the current grader. 

We dump them into a file, kinda like this

```
( 2) [PASS] testClass.testName
(10) [PASS] testclass.testName2
(20) [FAIL] testClass.testName3 - somethingException: file not found
```

Probably the easiest and most concise way to implement this feature

We might also want to think about including the raw gradleogs + stdout + stderr in a tarball and upload them to the comments as well. People can see a more detailed description of what went wrong, and if anything is completely screwed with the grader, a student would be able to send us the logs and let us know.

## 3 - HTML

Generate a nicer looking HTML page with with all the information from part 2, like test name, test weight, etc - kinda like what gradle generates for us, but slightly modified to include test weights.

Upload the generated HTML to some static hosting site using SCP 

The goal of this solution is ease of use essentially. Instead of having to download a text doc with all the test info, you can just click on a link and have all the info right there.

We could make it like Travis CI, and have different tabs for stdout, stderr, the failing tests, and a link to the raw logs.

URL could look something like http://gradelogs.zucchini.services/[SHA-1_hash_of_submission_contents]/

I don't think this would be as hard as it sounds.

Not gonna lie I really want to do the HTML thing.

**Comment by ausbin** [comment]
Jeuss Christ GitHub well done

**Comment by ausbin** [comment]
I was gonna do a breakdown as the comment and then upload a full grader log as an attachment

**Comment by pjztam** [comment]
I can do that as version 1

**Comment by ausbin** [comment]
Please do, thanks for the help

**Comment by pjztam** [comment]
done with #53
