### ISSUE TITLE
Store grading data in sqlite

### ISSUE THREAD

**Issue by ausbin** [zucchini/zucchini#55]
Patrick pointed out that our current metadata storage system has some issues:

1. It's expensive.

    To do an operation on all submissions, such as "show me all the grades" or "grade the broken submissions," we have to open() and parse 300+ JSON files. With sqlite, we just open() the database and do a query

2. It's not atomic.

    If serializing a dict to JSON fails, json raises a JSONDecodeError and stops writing halfway through the file. So when you try to startup Zucchini again, it fails We could avoid this by writing to a temp json file rename()ing it over the old one, but why

3. We can't save progress incrementally while grading.

    Right now, when an assignment has both interactive and noninteractive components, we grade the noninteractive components in parallel while prompting the user on the main thread for the interactive components. This means that we have to wait to save JSON files until both threads finish and we can merge the results. So if you ^C while grading, you lose 100% of your progress. If we write to the database as we go, then we avoid that

**Comment by skyman** [comment]
I'm actually worried about this one a little bit - I understand the problem but I kinda think that our fix is overkill, here's some reasons why:

Re. problem 1: This is correct. Doing all of that simultaneously does indeed cause a ton of overhead due to file opens. However it's only during the show/export phase that we need to load all of the JSON from scratch so I don't think it's too big an issue.

Re. problem 2: This can be solved by serializing the dict into a JSON string first and saving it onto the FS only if that works - assuming the JSON dicts do not grow too big to fit in memory. But then again that can't really happen seeing how the original dict has to reasonably fit in memory in the first place.

Re. problem 3: I don't see the reason why both threads wouldn't save to the JSON files. After all attaching a very simple locking mechanism on each submission object (the threading module provides one) it's extremely easy to make JSON saves thread-safe.

Overall it's a tradeoff: JSON provides very good flexibility in terms of moving graded submissions, manually editing grading results, adding or removing submissions, manually resetting submissions for regrading etc. with the single cost of speed. The speed cost is only noticeable when we're trying to export the grades (when you just want to see them at the end of grading they're already in memory anyway) and that's a process that I'm okay with costing additional time.

SQLite, on the other hand, provides good speed but makes the system a black box, where we'd need to add a ton of extra commands just to be able to modify the existing database of graded submissions. I don't think that's a friendly user experience and frankly I doubt the speed advantage is worth it - I feel like zucchini will be used more often for grading 20-30 submission classes versus 100+ submission ones, and I also feel like the flexibility the JSON files provide is actually useful for the target audience, especially for professors who likely will not know how to interact with SQLite files.

Obviously this is not a decision I make alone, but I strongly vote against switching from JSON to SQLite for storing graded submissions - it adds a ton of extra edge cases, we need to rewrite a ton of code to implement it, and the final result has the single disputable advantage of speed whereas it removes many possibilities that we provide with the JSON files that I would consider to be features.

**Comment by ausbin** [comment]
> SQLite, on the other hand, provides good speed but makes the system a black box,

It already is, really. The scores are stored as a bunch of nested lists. That's not really something you can edit easily. Like unless we change the format of JSON, it's not realistically human editable right now.

> where we'd need to add a ton of extra commands just to be able to modify the existing database of graded submissions. I don't think that's a friendly user experience

Editing the JSON right now isn't tbh

> and frankly I doubt the speed advantage is worth it - I feel like zucchini will be used more often for grading 20-30 submission classes versus 100+ submission ones, and I also feel like the flexibility the JSON files provide is actually useful for the target audience, especially for professors who likely will not know how to interact with SQLite files.

We need to add ways to edit grades better anyway, because overriding the grader is gonna be semi common imo. One idea I had was that it would auto-export to a spreadsheet, you edit the spreadsheet, and then it commits the changes. Similar to how [sudoedit](https://linux.die.net/man/8/sudoedit) works. That way we don't have to introduce weird commands like you're saying; we can just piggyback off folks' existing knowledge of editing spreadsheets

> Re. problem 3: I don't see the reason why both threads wouldn't save to the JSON files. After all attaching a very simple locking mechanism on each submission object (the threading module provides one) it's extremely easy to make JSON saves thread-safe.

I see what you mean here, but it kinda sucks to re-write every JSON file twice

> Obviously this is not a decision I make alone, but I strongly vote against switching from JSON to SQLite for storing graded submissions - it adds a ton of extra edge cases,

yea I wanna talk about this, it's not something i wanna do unilaterally since this is our thing, not mine in my view

> we need to rewrite a ton of code to implement it

If we use an ORM like SQLAlchemy, I don't think this is true. it's just a matter of using SQLAlchemy ORM models instead of the models we provide with our flaky homebrew ORM

> and the final result has the single disputable advantage of speed

And easier/more efficient querying and stuff. Right now we have everything in memory, which isn't really necessary

> whereas it removes many possibilities that we provide with the JSON files that I would consider to be features.

I just don't find them very easy to modify frankly. I think we need to provide better ways to edit grading results anyway before submitting, whether we use JSON or SQLite

**Comment by skyman** [comment]
I do realize that the biggest problem with having everything in memory is that after some point it's not unimaginable that with enough submissions on a complicated assignment, logs etc. might cause the grading computer to run out of memory. That's a pretty bad result.

Apart from that, I do agree with the readability concerns with JSON but then would propose as an alternative switching to YAML for that too instead of SQLite. That would be easily editable at a slightly higher cost of reading/writing.

On the other hand, I like the idea of allowing the editing of the data as a spreadsheet after the grading has been done. The obvious way to do that is using a CSV file we would generate, which essentially every spreadsheet app nowadays is capable of opening. The exporters then would use this CSV file rather than the individual grade data in the directories. In that case, however, the JSON files in the directories becomes entirely redundant, and without those files it's much harder to maintain a Filesystem <-> Zucchini Object link. While SQLite is good for the interim representation and storing of the grades, I don't see how it would be helpful with allowing the grader to review the grades as a spreadsheet without the use of usually badly-designed SQLite Browser software.

**Comment by ausbin** [comment]
nope
